stages:
  prep_sod_data:
    cmd: python src/data/prep_sod.py
    deps:
      - src/data/prep_sod.py
      - data/raw/CarDD_release/CarDD_SOD/
    outs:
      - data/processed/sod/

  train_sod_model:
    cmd: python src/train/train_sod.py --train_config configs/train/stage1-sod.yaml --data_config data/processed/sod/sod_data.yaml
    deps:
      - src/train/train_sod.py
      - configs/train/stage1-sod.yaml
      - data/processed/sod/
    outs:
      - artifacts/models/stage1_sod/

  consolidate_data:
    cmd: python src/data/consolidate.py --config configs/data/Experiment_v1.yaml
    deps:
      - src/data/consolidate.py
      - configs/data/Experiment_v1.yaml
      - data/raw/
    outs:
      - data/processed/yolo_seg/

  train_model:
    cmd: python src/train/train.py --config configs/train/yolo26n-seg.yaml
    deps:
      - src/train/train.py
      - configs/train/yolo26n-seg.yaml
      - data/processed/yolo_seg/
    outs:
      - artifacts/models/yolo26n-seg/
