stages:
  prep_sod_data:
    cmd: python src/data/prep_sod.py
    deps:
      - src/data/prep_sod.py
      - data/raw/CarDD_release/CarDD_SOD/
    outs:
      - data/processed/sod/

  tile_data:
    cmd: PYTHONPATH=. python src/data/create_tiles.py --config configs/pipeline_config.yaml
    deps:
      - src/data/create_tiles.py
      - data/processed/sod/
      - configs/pipeline_config.yaml
    params:
      - configs/pipeline_config.yaml:
        - dataset.overlap_percent
    outs:
      - data/processed/sod_tiled/

  train:
    cmd: PYTHONPATH=. python src/train/train.py --config configs/pipeline_config.yaml
    deps:
      - src/train/train.py
      - data/processed/sod_tiled/
      - configs/pipeline_config.yaml
    params:
      - configs/pipeline_config.yaml:
        - project.name
        - project.run_name
        - model.preset
        - model.epochs
        - dataset.batch_size
        - dataset.imgsz
        - pipeline.loss_type
        - pipeline.fl_gamma
        - pipeline.task
    outs:
      - car_defect_detection/stage1_focal_yolo26n_run/
