"""Serve defect crop images generated by the pipeline."""
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse

from app.config import settings

router = APIRouter(prefix=settings.api_v1_str, tags=["crops"])


@router.get("/crops/{filename}")
def get_crop(filename: str):
    """Serve a defect crop image by filename from the crops storage directory."""
    # Guard against path traversal.
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid filename"
        )
    crop_path = settings.crops_dir / filename
    if not crop_path.exists() or not crop_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Crop not found"
        )
    return FileResponse(crop_path, media_type="image/png")
