vars:
  - configs/pipeline_config.yaml

stages:
  prep_sod_data:
    cmd: python src/data/prep_sod.py
    deps:
      - src/data/prep_sod.py
      - data/raw/CarDD_release/CarDD_SOD/
    outs:
      - data/processed/sod/

  tile_data:
    cmd: PYTHONPATH=. python src/data/create_tiles.py --config configs/pipeline_config.yaml
    deps:
      - src/data/create_tiles.py
      - data/processed/sod/
      - configs/pipeline_config.yaml
    params:
      - configs/pipeline_config.yaml:
        - dataset.overlap_percent
    outs:
      - data/processed/sod_tiled/

  train:
    cmd: PYTHONPATH=. python src/train/train.py --config configs/pipeline_config.yaml
    deps:
      - src/train/train.py
      - data/processed/sod_tiled/
      - configs/pipeline_config.yaml
    params:
      - configs/pipeline_config.yaml:
        - project.name
        - project.run_name
        - model.preset
        - model.epochs
        - dataset.batch_size
        - dataset.imgsz
        - pipeline.loss_type
        - pipeline.fl_gamma
        - pipeline.task
    outs:
      - ${project.name}/${project.run_name}/

  evaluate:
    cmd: PYTHONPATH=. python src/eval/validate.py --config configs/pipeline_config.yaml
    deps:
      - src/eval/validate.py
      - ${project.name}/${project.run_name}/
      - configs/pipeline_config.yaml
      - configs/data/val_splits.yaml
    params:
      - configs/pipeline_config.yaml:
        - gating_thresholds.pixel_thresh_high
        - gating_thresholds.pixel_thresh_low
        - gating_thresholds.min_cc_area
        - gating_thresholds.max_cc_area_reject
