# Task Meta
task: segment
loss_type: focal
fl_gamma: 2.0
model_preset: yolo26m-seg.pt
project_name: car_defect_detection
run_name: yolo26m_640_stage2_clean_data_tiling
multi_scale: true

# Dataset Paths
dataset_config: "data/processed/stage2_clean_data_tiling/data.yaml"

epochs: 100
imgsz: 640
batch_size: 8
patience: 15
device: 0
workers: 8
amp: true
freeze: 15
lr0: 0.01
lrf: 0.01

augmentations:
  hsv_h: 0.03
  hsv_s: 0.4
  hsv_v: 0.5
  degrees: 15.0
  scale: 0.2
  perspective: 0.0005
  fliplr: 0.5
  mosaic: 0.0
  mixup: 0.0
  erasing: 0.2
  close_mosaic: 0
