# Task Meta
task: segment
model_preset: yolo26s-seg.pt
project_name: car_defect_detection
run_name: yolo26s_1280_v2

# Dataset Paths
dataset_config: "data/processed/Experiment_v1/data.yaml"

# Hardware / Performance Parameters
epochs: 5         # Keeping it at 5 for the fast comparative pipeline test
imgsz: 1280       # High-res experiment specification
batch_size: 4     # Reduced to fit massive 1280px tensors in VRAM
device: 0
workers: 4
amp: true         # Enable Tensor Cores for speed

# Environmental Defense Augmentations
augmentations:
  hsv_h: 0.03
  hsv_s: 0.7
  hsv_v: 0.5
  degrees: 10.0
  scale: 0.5
  perspective: 0.0005
  fliplr: 0.5
  mosaic: 0.3
  mixup: 0.1
  erasing: 0.4
  close_mosaic: 10
