task: segment
loss_type: focal
fl_gamma: 2.0
fl_alpha: 0.50
fl_scale: 1.0

model_preset: /home/lamacpp/secure_workspace/car_defect_detection/runs/segment/model5_resume_adapt/stage1_head_warmup-3/weights/best.pt

project_name: model5_resume_adapt
run_name: stage2_differential_finetune

multi_scale: true

dataset_config: "/home/lamacpp/Documents/car_defect_detection/data/processed/yolo_seg_clean_2200_/dataset.yaml"

epochs: 120
imgsz: 1024
batch_size: 4
patience: 20
device: 0
workers: 8
amp: true
freeze: 0

lr0: 0.001
lrf: 0.01
optimizer: SGD

differential_lr: true
split_layer_idx: 15
backbone_lr_mult: 0.1

augmentations:
  hsv_h: 0.03
  hsv_s: 0.4
  hsv_v: 0.5
  degrees: 30.0
  scale: 0.5
  perspective: 0.0005
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  erasing: 0.4
  close_mosaic: 25
